services:
  hawser:
    image: ghcr.io/finsys/hawser:latest
    container_name: hawser
    restart: unless-stopped
    privileged: true # can't connect to podman socket without this...
    ports:
      - 2376:2376
    env_file:
      - ./hawser/.env
      # Required fields in './hawser/.env':
      # TOKEN    = Hawser token used for authentication.
    environment:
      AGENT_NAME: Homelab Outpost
      TLS_CERT: /certs/hawser/hawser.crt
      TLS_KEY: /certs/hawser/hawser.key
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:Z
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./hawser/certificates:/certs/hawser:ro,Z

  pangolin:
    image: docker.io/fosrl/pangolin:ee-latest # https://github.com/fosrl/pangolin/releases
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./pangolin/config:/app/config:Z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "10s"
      timeout: "10s"
      retries: 15
    networks:
      - pangolin_net

  gerbil:
    image: docker.io/fosrl/gerbil:latest # https://github.com/fosrl/gerbil/releases
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ./pangolin/config/:/var/config:Z
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 21820:21820/udp
      - 51820:51820/udp
      - 3004:3004/tcp
      - 80:80
      - 443:443
    networks:
      - pangolin_net

  traefik:
    image: docker.io/traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    env_file:
      - ./pangolin/.env
      # Required fields in './pangolin/.env':
      # OVH_ENDPOINT           = OVH credentials for DNS challenge.
      # OVH_APPLICATION_KEY    = OVH credentials for DNS challenge.
      # OVH_APPLICATION_SECRET = OVH credentials for DNS challenge.
      # OVH_CONSUMER_KEY       = OVH credentials for DNS challenge.
    volumes:
      - ./pangolin/config/traefik:/etc/traefik:Z,ro
      - ./pangolin/config/letsencrypt:/letsencrypt:Z
      - ./pangolin/config/traefik/logs:/var/log/traefik:Z
    network_mode: service:gerbil

networks:
  pangolin_net:
    name: pangolin_net
