services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    ports:
      - 51820:51820/udp
      - 443:443 # for caddy
      - 80:80   # for caddy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      PEERS: homelab
      ALLOWEDIPS: 10.13.13.1,10.13.13.2
      PERSISTENTKEEPALIVE_PEERS: homelab
      # SERVER_ALLOWEDIPS_PEER_homelab:
    volumes:
      - ./wireguard/config:/config:Z
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1

  caddy:
    build:
      dockerfile: ./caddy/Dockerfile
      context: ./
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ./caddy/.env
      # Required fields in './caddy/.env':
      # DOMAIN_NAME = The domain name used for this VPS.
      # REDIRECT_DOMAIN_NAME = The domain name which wil be redirected to DOMAIN_NAME.
      #                        Useful if TLS challenge cannot be done easily for REDIRECT_DOMAIN_NAME.
      # OVH_APPLICATION_KEY    = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_APPLICATION_SECRET = Generated in OVH dashboard, required for TLS challenge (HTTPS).
      # OVH_CONSUMER_KEY       = Generated in OVH dashboard, required for TLS challenge (HTTPS).
    volumes:
      - ./caddy/config:/etc/caddy:Z
      - ./caddy/logs:/logs:Z
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "service:wireguard"

  hawser:
    image: ghcr.io/finsys/hawser:latest
    container_name: hawser
    restart: unless-stopped
    privileged: true # can't connect to podman socket without this...
    ports:
      - 2376:2376
    env_file:
      - ./hawser/.env
      # Required fields in './hawser/.env':
      # TOKEN    = Hawser token used for authentication.
    environment:
      AGENT_NAME: Homelab Outpost
      TLS_CERT: /certs/hawser/hawser.crt
      TLS_KEY: /certs/hawser/hawser.key
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:Z
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./hawser/certificates:/certs/hawser:ro,Z

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  wireguard_net:
    name: wireguard_net
